#!/bin/sh

# Run Clang-Format
for file in `git diff-index --cached --name-only HEAD | grep -iE '\.(cpp|cc|h|hpp)$'` ; do
  clang-format -i $file
  git add $file
done

# Try to compile
pushd build
if ! meson compile; then
  exit 1
fi
popd

exit 0
