#ifndef COMMON_STAGES_ISOBOOT_H
#define COMMON_STAGES_ISOBOOT_H

#define ISOBOOT_ADDRESS  0x10000
#define ISOBOOT_PRE_SIZE (2 * 1024)
#define ISOBOOT_SIZE     (64 * 1024)

#define ISOBOOT_SEGMENT  (ISOBOOT_ADDRESS >> 4)
#define ISOBOOT_STACK    (ISOBOOT_PRE_SIZE & -16)

#endif
