#ifndef COMMON_STAGES_MBR_H
#define COMMON_STAGES_MBR_H

#define MBR_ADDRESS           0x7C00
#define MBR_SEGMENT           (MBR_ADDRESS >> 4)

#define MBR_STACK_BOT_ADDRESS 0x500
#define MBR_STACK_TOP_ADDRESS (MBR_ADDRESS - 16)
#define MBR_STACK_SEGMENT     (MBR_STACK_BOT_ADDR >> 4)
#define MBR_STACK_ADDRESS     (MBR_STACK_TOP_ADDRESS - MBR_STACK_BOT_ADDRESS)

#endif // !COMMON_STAGES_MBR_H
