set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR 8086)

# Assembler
find_program(CMAKE_ASM_COMPILER nasm REQUIRED)
set(CMAKE_ASM_COMPILE_OBJECT "<CMAKE_ASM_COMPILER> <FLAGS> -o <OBJECT> <SOURCE>")
set(CMAKE_ASM_LINK_EXECUTABLE "<CMAKE_LINKER> <LINK_FLAGS> -o <TARGET> <OBJECTS>")
set(CMAKE_ASM_FLAGS "-f elf32")
set(CMAKE_ASM_FLAGS_DEBUG "-O0")
set(CMAKE_ASM_FLAGS_RELEASE "-Ox")

# C Compiler
find_program(CMAKE_C_COMPILER smlrcc REQUIRED)
set(CMAKE_C_COMPILE_OBJECT "<CMAKE_C_COMPILER> <INCLUDES> <FLAGS> -o <OBJECT> -c <SOURCE>")
set(CMAKE_C_LINK_EXECUTABLE "<CMAKE_LINKER> <LINK_FLAGS> -o <TARGET> <OBJECTS>")
set(CMAKE_C_FLAGS "-Wall -flat16")

set(CMAKE_C_COMPILER_WORKS TRUE)

# Linker
find_program(CMAKE_LINKER smlrl REQUIRED)
set(CMAKE_EXE_LINKER_FLAGS "-flat16 -origin 0x0000")
