name: Build
on: 
  push:
    branches:
      - "master"
      - "dev"
  pull_request:
    branches:
      - "master"
      - "dev"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          path: project

      - name: Install dependencies
        uses: ./project/.github/actions/depend
        with:
          install_nasm: true
