name: Security Check
on:
  push:
    branches: 
      - dev
    paths:
      - "**.c"
      - "**.h"
      - "**.cpp"
      - "**.hpp"
  pull_request:
    branches: 
      - dev
    paths:
      - "**.c"
      - "**.h"
      - "**.cpp"
      - "**.hpp"
  workflow_dispatch:
permissions:
  contents: read
  security-events: write
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run clang-format lint
        uses: DoozyX/clang-format-lint-action@v0.16.2
        with:
          clangFormatVersion: 15
  security_scan:
    name: Code security scan
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Codacy analyze
        uses: codacy/codacy-analysis-cli-action@master
        with:
          output: results.sarif
          format: sarif
          gh-code-scanning-compat: true
          max-allowed-issues: 2147483647
      
      - name: Upload scan results
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: results.sarif
